### ISSUE TITLE
Restore tests: Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

### ISSUE THREAD

**Issue by G-Ray** [QwantResearch/masq-app#25]
When renaming `src/Storyshots.test.bak` to `src/Storyshots.test.js` to restore the tests, I get:

`FAIL  src/Storyshots.test.js
  ● Test suite failed to run

    Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "/home/gbonneville/src/masq-app/node_modules/babel-preset-react-app/index.js")
      
      at throwVersionError (node_modules/@babel/helper-plugin-utils/lib/index.js:62:11)
      at Object.assertVersion (node_modules/@babel/helper-plugin-utils/lib/index.js:11:11)
      at node_modules/@babel/plugin-transform-destructuring/lib/index.js:11:7
      at node_modules/@babel/helper-plugin-utils/lib/index.js:16:12
      at Function.memoisePluginContainer (node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
      at Function.normalisePlugin (node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
          at Array.map (<anonymous>)
      at Function.normalisePlugins (node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
      at node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
          at Array.map (<anonymous>)
      at OptionManager.resolvePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
      at OptionManager.mergePresets (node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)
`

**Comment by G-Ray** [comment]
See https://github.com/storybooks/storybook/issues/3335

**Comment by G-Ray** [comment]
https://github.com/storybooks/storybook/issues/3335

**Comment by G-Ray** [comment]
https://github.com/storybooks/storybook/issues/3335

**Comment by G-Ray** [comment]
Fixed with 06f960aa0c3ab5ae609797c93887b7a5c145851e
